### PR TITLE
Add Get Current Places

### PR DESCRIPTION
**Pull request by pdruart**
Add this method for nearby places from device location

### CODE REVIEW

**Comment by tolu360** [comment]
Hi @pdruart, thank you for the effort - I apologize for not getting back earlier than now. I have been very busy lately. I just want to clear out some things with you before this can be pulled in.

1. This API does not necessarily return `nearby places from device location`. It returns the [device's currently-reported location](https://developers.google.com/places/android-api/current-place) with the degree of `likelihood`, hence the multiple places it returns. So the formatted response from this package must correctly depict that fact. I was thinking along the lines of ...

```Json
[{ name: 'Facebook HQ',
  website: 'https://www.facebook.com/',
  longitude: -122.14835169999999,
  address: '1 Hacker Way, Menlo Park, CA 94025, USA',
  latitude: 37.48485,
  placeID: 'ChIJZa6ezJa8j4AR1p1nTSaRtuQ',
  types: [ 'street_address', 'geocode' ],
  phoneNumber: '+1 650-543-4800'
  likelihood: 0.55 
},
{ name: 'Another Place',
  website: 'https://www.facebook.com/',
  longitude: -122.14835169999999,
  address: '1 Hacker Way, Menlo Park, CA 94025, USA',
  latitude: 37.48485,
  placeID: 'ChIJZa6ezJa8j4AR1p1nTSaRtuQ',
  types: [ 'street_address', 'geocode' ],
  phoneNumber: '+1 650-543-4800'
  likelihood: 0.35 
}]
```
Notice how summing up the different likelihood adds up to 1?

2. You also need to pay close attention to naming conventions (variables and methods) used. The appropriate APIs must also be used e.g. on android, `AutocompletePredictionBuffer` cannot be used in place of `PlaceLikelihoodBuffer`, likewise, `getCurrentPlace` should be called off of `PlaceDetectionApi` etc.

You may update the PR with these stuff in place, if it's not too much work for you. Thanks for this contribution.

Cheers!
    .

**Comment by pdruart** [comment]
Hi @tolu360 , thank you for taking the time to watch this PR. I can not do that this week but I'll send it to you next week. thanks for your time

**Comment by tolu360** [comment]
Thanks @pdruart

**Comment by pdruart** [comment]
I think everything is good. I change the naming as well as the standard google api place with the likelihood.
On the other hand I am not totally sure for the android, if someone can take a look it would be cool

**Comment by pdruart** [comment]
all works ;) (android / ios)

**Comment by tolu360** [comment]
Thanks for following up with your PR @pdruart, I'd pull this in and add a few tweaks as soon as I'm back from a short vacation. Cheers!

**Comment by tolu360** [comment]
Hello @pdruart - thank you for your patience the whole time, I'm trying to pull this PR in finally but we now have some conflicts. Do you think you can make commits to fix things against master? Would be glad if you can quickly do that. Cheers!

**Comment by pdruart** [comment]
Done

**Comment by tolu360** [comment]
Thanks

**Comment by tolu360** [comment]
Pulled in with a few naming tweaks - would note that in the commit! Thanks man!

**Pull request closed without merging**
