### PR TITLE
Bug fixes and API improvements

### PR DESCRIPTION
**Pull request by hammadj**
- iOS Bug Fix so that only the current modal is dismissed
- Add coordinate params to openAutocompleteModal and getAutocompletePredictions
- Add radius param to allow customizing bounds/viewport

### CODE REVIEW

**Comment by tolu360** [comment]
Hello Hammad @hammadj, thanks for the work you've put into this PR - most especially for helping to support v1. Yours would be the first PR to cater also to v1. I'd review your changes and pull this in asap!

Cheers man!

**Comment by temitope** [comment]
What the difference between this PR ( #22 ) and #23?

**Comment by tolu360** [comment]
#22 is for v2+(RN 0.40+) while #23 is for v1+(RN <= 0.39), to compensate for the breaking changes introduced with `RN v0.40` (namespaces for iOS core files), I had to separate the builds to continue to make the library work with older projects.

**Comment by hammadj** [comment]
@tolu360 you're very welcome, and thanks for the work you put into this library, very well put together!

And yea the two PRs are identical except for the fact that the other one is for the v1 branch

**Comment by tolu360** [comment]
Hi @hammadj, all pulled in already - had to fix a few regressions introduced by a few typos however, such as repeating the call to `PlaceAutocomplete.IntentBuilder` for `openPlacePickerModal()` rather than `PlacePicker.IntentBuilder`. That was just an easy fix, too small to bother you.

Thanks for the PR once again - nice work!

**Comment by hammadj** [comment]
@tolu360 Whoops my bad, thanks for fixing it and thanks for the merge :)

**Pull request merged**
