### PR TITLE
Fix the app crash when the user hit `select` button before the map load

### PR DESCRIPTION
**Pull request by Moumene**
Verify if `getAddress` is not empty or null before calling `toString()`

### CODE REVIEW

**Comment by tolu360** [comment]
I see what you mean @Moumene, thanks!

**Comment by Moumene** [comment]
Welcome @tolu360 :)

**Comment by chrusart** [comment]
I've include this fix in my pull request #52 as I change the file significantly.

**Comment by tolu360** [comment]
Thanks pulled in via #58

**Pull request closed without merging**
