### PR TITLE
Add places type in response.

### PR DESCRIPTION
**Pull request by Richou**

### CODE REVIEW

**Comment by tolu360** [comment]
Nice work @Richou, haven't thoroughly reviewed the PR but it seems you have a typo on `RNGooglePlaces.m` around line 107 where you have `result.types` as against `place.types`. Do you want to quickly fix that before I pull this in or I should just go ahead?

Thanks!

**Comment by Richou** [comment]
Oops, yes my mistake, I will fix that tonight. Sorry !

Thanks !

**Comment by Richou** [comment]
Ok, I fixed it. 

Thanks.

**Comment by tolu360** [comment]
Thanks @Richou for the PR, the changes would be published soon. Just out of curiosity, are you using `place types` in your project currently?

Cheers!

**Comment by Richou** [comment]
Cool thanks !
Yes I'm using it, I would like to display different icons depending on the place types.

Regards !

**Pull request merged**
