### PR TITLE
Google API Client connection failure auto resolve

### PR DESCRIPTION
**Pull request by chrusart**
When user have disabled permissions for Google Play Services (even for SMS or Camera) google api client stops working and connect failures. This can happen on many other connection failures and if there is an auto resolution, system can display proper message with link to settings if applicable.
On failure ConnectionResult can try to show auto resolve activity (.startResolutionForResult) and then connect after user enables needed permissions.

I didn't find any other way to make Google API Client working without granting this permissions.
The thing is that there is no need when calling REST Web API and get places without any permissions granted to Google Play Services on device of course.

Google API Client connects on module creation, there is I guess race between creating an activity (attaching to react context) and connection failure (without permissions) and then we don't have activity attached to react context when connection failures on app start. If we have attached activity auto resolve activity will show on application start. I tried to make client to connect in the state when we have for sure activity for example in onStart() lifecycle event but we don't have this in LifecycleEventListener interface and I dropped it. Not sure if activity can not be attached to react context by other reasons on app start.

### CODE REVIEW

**Comment by chrusart** [comment]
Is something i should still do?

What do you think about this PR?

**Comment by Samykills** [comment]
am getting this error with the plugin

java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"

how can i clone our branch directly using npm to my project?
(am new with npm and stuff kindly ignore my noobness :)

**Comment by chrusart** [comment]
@tolu360 , do you review PRs? Should I do something more here?

**Comment by tolu360** [comment]
Thanks for updating your PR, I would review and pull this in (or let you know if there's anything else to do on it) as soon as possible. Cheers

**Pull request merged**
