### PR TITLE
support build for react native >= 0.59

### PR DESCRIPTION
**Pull request by congnguyen91**
- Hi Tolu :) 

This PR is for react native 0.59. Cause of some modules need customize supportLibVersion to void conflict

Please check again & merge it :) . thanks
- Cong -

### CODE REVIEW

**Comment by marcosandri-dev** [comment]
For me it is totally ok!! It saved my project, I'm using React 0.51.1; Please merge!

**Comment by atulmy** [comment]
@tolu360 kindly merge this as this solves issue with `react-native-google-places@beta`

**Comment by VitorBrangioni** [comment]
don't work for me. Project is build with success, but app open and close without error. Any solution?

**Comment by congnguyen91** [comment]
@VitorBrangioni depend on your gradle configuration :) for react-native >=59. Gradle Tool classPath >= 3.3.1, and other libs, modules, etc. There are many dependencies are updated with it :) This is for almost supported configuration. Keep it going thanks :D

**Comment by shide1989** [comment]
Works for me, thanks !!!!

**Comment by isaiahols** [comment]
Works perfect for me! Thank you!! I am using RN 0.59.8
Please Merge with `react-native-google-places@beta`

**Comment by congnguyen91** [comment]
You are welcome :) all you can follow me on Github like a thank 👯‍♂

**Comment by Eramirez06** [comment]
Works Nice, im using RN 0.59.5 thanks bro.

**Comment by tolu360** [comment]
Hi @congnguyen91, I have been super busy but I would make out time to merge this in tomorrow. Thanks for the PR!

**Comment by isaiahols** [comment]
Today is the day!!! @tolu360 Thanks in advance for merging this one :)

**Pull request merged**
