### PR TITLE
Added podspec

### PR DESCRIPTION
**Pull request by nabati**
Added podspec to make it easier to manage the dependencies.

### CODE REVIEW

**Comment by tolu360** [comment]
Thank you @poyannabati

**Comment by tlvenn** [comment]
any chance to merge this @tolu360 ?

**Comment by timonibus** [comment]
Thanks a lot for this library, I appreciate it a lot. I am using CocoaPods and it would be really nice if this could be merged.

**Comment by AvenzaOleg** [comment]
For those who is waiting for this merge request to get accepted and does not want to fork the repo - you can setup a directory with the podspec file from this merge request and a symlink pointing to node_modules/react-native-google-places

**Comment by aforty** [comment]
Can we get this added @tolu360? Manually linking this library is a chore I'd rather not have to deal with.

**Comment by tolu360** [comment]
@aforty I have not had to do manual linking for the library before - running `react-native link` had always been enough for me. Have you always manually linked this library in your projects?

So I can take a look and add this in if 1. the PR is updated and made against the appropriate branch (v2/v3) and 2. you or the PR author would stick around to help resolve issues around the podspec

**Comment by aforty** [comment]
Sorry let me clarify. I'm not manually linking but rather running `react-native link` does a manual link and I've found those links to be error prone and unstable in a large project. I, and others, much prefer to maintain dependencies using cocoa pods and as such I'd love to make that an option here. I can take over this PR and stand behind it should something go wrong.

**Comment by tolu360** [comment]
Fair enough, I would gladly consider the updated PR, thanks.

**Pull request closed without merging**
